### ISSUE TITLE
Big error after first start

### ISSUE THREAD

**Issue by Jugulaire** [CachetHQ/Docker#213]
Hi, 

I'm trying to install cachet on Docker but i have a big issue :
```
Starting cachetdocker_postgres_1 ... 
Starting cachetdocker_postgres_1 ... done
Recreating cachetdocker_cachet_1 ... 
Recreating cachetdocker_cachet_1 ... done
Attaching to cachetdocker_postgres_1, cachetdocker_cachet_1
postgres_1  | LOG:  database system was shut down at 2017-06-20 15:00:23 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
cachet_1    | Initializing Cachet container ...
cachet_1    | PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data in /var/www/html/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:68
cachet_1    | Stack trace:
cachet_1    | #0 /var/www/html/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(68): random_bytes(16)
cachet_1    | #1 /var/www/html/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(56): GrahamCampbell\Exceptions\ExceptionIdentifier->generate()
cachet_1    | #2 /var/www/html/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Exception))
cachet_1    | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Exception))
cachet_1    | #4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Exception))
cachet_1    | #5 {main}
cachet_1    |   thrown in /var/www/html/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 68
cachet_1    | PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data in /var/www/html/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:68
cachet_1    | Stack trace:
cachet_1    | #0 /var/www/html/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(68): random_bytes(16)
cachet_1    | #1 /var/www/html/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(56): GrahamCampbell\Exceptions\ExceptionIdentifier->generate()
cachet_1    | #2 /var/www/html/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
cachet_1    | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
cachet_1    | #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\E in /var/www/html/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 68
cachetdocker_cachet_1 exited with code 255
```
Here is my docker-compose.yml : 
> Note : in the install guide it is specified that you need to modify the env variables but i don't know how 
```
  1 version: "3"
  2 
  3 services:
  4   postgres:
  5     image: postgres:9.5
  6     volumes:
  7       - /var/lib/postgresql/data
  8     environment:
  9       - POSTGRES_USER=postgres
 10       - POSTGRES_PASSWORD=postgres
 11     restart: always
 12   cachet:
 13     build:
 14       context: .
 15       args:
 16         - cachet_ver=v2.3.11
 17     ports:
 18       - 8000:8000
 19     links:
 20       - postgres:postgres
 21     environment:
 22       - DB_DRIVER=postgres
 23       - DB_HOST=postgres
 24       - DOCKER=true
 25       - DB_PORT=5432
 26       - DB_DATABASE=postgres
 27       - DB_USERNAME=postgres
 28       - DB_PASSWORD=postgres
 29       - DB_PREFIX=chq_
 30       - APP_KEY=${APP_KEY:-null}
 31       - DEBUG=false
 32     depends_on:
 33       - postgres
 34     restart: always
```
Can you help me ?

**Comment by wfjsw** [comment]
Solution:
Upgrade PHP to latest version.

**Comment by Jugulaire** [comment]
Hi,
in my Docker file i have PHP7 :
```
# Using repo packages instead of compiling from scratch
 13 RUN apk add --no-cache --update \
 14     postgresql-client \
 15     postgresql \
 16     mysql-client \
 17     php7 \
 18     php7-apcu \
 19     php7-bcmath \
 20     php7-dom \
 21     php7-ctype \
 22     php7-curl \
 23     php7-fpm \
 24     php7-gd \
 25     php7-iconv \
 26     php7-intl \
 27     php7-json \
 28     php7-mbstring \
 29     php7-mcrypt \
 30     php7-mysqlnd \
 31     php7-opcache \
 32     php7-openssl \
 33     php7-pdo \
 34     php7-pdo_mysql \
 35     php7-pdo_pgsql \
 36     php7-pdo_sqlite \
 37     php7-phar \
 38     php7-posix \
 39     php7-session \
 40     php7-soap \
 41     php7-xml \
 42     php7-zip \
 43     php7-zlib \
 44     wget sqlite git sudo curl bash grep \
 45     supervisor
```

**Comment by wfjsw** [comment]
Yes you have to upgrade to 7.1.3 or above. Just wait for new packages.

**Comment by madhur** [comment]
I have the same issue
