### ISSUE TITLE
Internal Server Error on manually starting docker container for cachet

### ISSUE THREAD

**Issue by ajinkyasuryawanshi-okta** [CachetHQ/Docker#223]
On an ec2 instance with docker installed, I ran following command manually 
```
docker run -d --name cachet \
  -p 80:8000 \
  -e DB_DRIVER=mysql \
  -e DB_HOST=REDACTED \
  -e DB_DATABASE=REDACTED \
  -e DB_USERNAME=REDACTED \
  -e DB_PASSWORD=REDACTED \
  -e APP_KEY=GWkHxlnV8dWztJTOaXNzFfMr1cBaZMvveonTKIs0mXg= \
  -e DEBUG=true \
  -d cachethq/docker:2.3.12
```
But it constantly gives a 500 for setup page for url http://{dockerhostip}/setup 
![image](https://user-images.githubusercontent.com/10985665/28848984-c8ff9960-76c9-11e7-9267-f5e145f8af1a.png)

```
sudo docker logs -f 55539f244f36
+ start_system
+ initialize_system
+ echo 'Initializing Cachet container ...'
+ APP_KEY=GWkHxlnV8dWztJTOaXNzFfMr1cBaZMvveonTKIs0mXg=
+ APP_ENV=development
+ APP_DEBUG=true
+ APP_URL=http://localhost
+ DB_DRIVER=mysql
+ DB_HOST=REDACTED
+ DB_DATABASE=REDACTED
+ DB_PREFIX=
+ DB_USERNAME=REDACTED
+ DB_PASSWORD=REDACTED
+ [[ mysql = \p\g\s\q\l ]]
+ [[ mysql = \m\y\s\q\l ]]
+ DB_PORT=3306
+ DB_PORT=3306
+ CACHE_DRIVER=apc
+ SESSION_DRIVER=apc
+ QUEUE_DRIVER=database
+ CACHET_EMOJI=false
+ CACHET_BEACON=true
+ CACHET_AUTO_TWITTER=true
+ MAIL_DRIVER=smtp
+ MAIL_HOST=localhost
+ MAIL_PORT=25
+ MAIL_USERNAME=null
+ MAIL_PASSWORD=null
+ MAIL_ADDRESS=null
+ MAIL_NAME=null
+ MAIL_ENCRYPTION=null
+ REDIS_HOST=null
Initializing Cachet container ...
+ REDIS_DATABASE=null
+ REDIS_PORT=null
+ REDIS_PASSWORD=null
+ GITHUB_TOKEN=null
+ NEXMO_KEY=null
+ NEXMO_SECRET=null
+ NEXMO_SMS_FROM=Cachet
+ PHP_MAX_CHILDREN=5
+ [[ GWkHxlnV8dWztJTOaXNzFfMr1cBaZMvveonTKIs0mXg= == null ]]
+ sed 's,{{APP_KEY}},GWkHxlnV8dWztJTOaXNzFfMr1cBaZMvveonTKIs0mXg=,g' -i /var/www/html/.env
+ sed 's,{{APP_ENV}},development,g' -i /var/www/html/.env
+ sed 's,{{APP_DEBUG}},true,g' -i /var/www/html/.env
+ sed 's,{{APP_URL}},http://localhost,g' -i /var/www/html/.env
+ sed 's,{{DB_DRIVER}},mysql,g' -i /var/www/html/.env
+ sed 's,{{DB_HOST}},REDACTED,g' -i /var/www/html/.env
+ sed 's,{{DB_DATABASE}},REDACTED,g' -i /var/www/html/.env
+ sed 's,{{DB_PREFIX}},,g' -i /var/www/html/.env
+ sed 's,{{DB_USERNAME}},REDACTED,g' -i /var/www/html/.env
+ sed 's,{{DB_PASSWORD}},REDACTED,g' -i /var/www/html/.env
+ sed 's,{{DB_PORT}},3306,g' -i /var/www/html/.env
+ sed 's,{{CACHE_DRIVER}},apc,g' -i /var/www/html/.env
+ sed 's,{{SESSION_DRIVER}},apc,g' -i /var/www/html/.env
+ sed 's,{{QUEUE_DRIVER}},database,g' -i /var/www/html/.env
+ sed 's,{{CACHET_EMOJI}},false,g' -i /var/www/html/.env
+ sed 's,{{CACHET_BEACON}},true,g' -i /var/www/html/.env
+ sed 's,{{CACHET_AUTO_TWITTER}},true,g' -i /var/www/html/.env
+ sed 's,{{MAIL_DRIVER}},smtp,g' -i /var/www/html/.env
+ sed 's,{{MAIL_HOST}},localhost,g' -i /var/www/html/.env
+ sed 's,{{MAIL_PORT}},25,g' -i /var/www/html/.env
+ sed 's,{{MAIL_USERNAME}},null,g' -i /var/www/html/.env
+ sed 's,{{MAIL_PASSWORD}},null,g' -i /var/www/html/.env
+ sed 's,{{MAIL_ADDRESS}},null,g' -i /var/www/html/.env
+ sed 's,{{MAIL_NAME}},null,g' -i /var/www/html/.env
+ sed 's,{{MAIL_ENCRYPTION}},null,g' -i /var/www/html/.env
+ sed 's,{{REDIS_HOST}},null,g' -i /var/www/html/.env
+ sed 's,{{REDIS_DATABASE}},null,g' -i /var/www/html/.env
+ sed 's,{{REDIS_PORT}},null,g' -i /var/www/html/.env
+ sed 's,{{REDIS_PASSWORD}},null,g' -i /var/www/html/.env
+ sed 's,{{GITHUB_TOKEN}},null,g' -i /var/www/html/.env
+ sed 's,{{NEXMO_KEY}},null,g' -i /var/www/html/.env
+ sed 's,{{NEXMO_SECRET}},null,g' -i /var/www/html/.env
+ sed 's,{{NEXMO_SMS_FROM}},Cachet,g' -i /var/www/html/.env
+ sudo sed 's,{{PHP_MAX_CHILDREN}},5,g' -i /etc/php7/php-fpm.d/www.conf
+ rm -rf 'bootstrap/cache/*'
+ chmod -R 777 storage
+ check_database_connection
+ echo 'Attempting to connect to database ...'
+ case "${DB_DRIVER}" in
+ prog='mysqladmin -h REDACTED -u REDACTED -pREDACTED -P 3306 status'
+ timeout=60
+ mysqladmin -h REDACTED -u REDACTED -pREDACTED -P 3306 status
Attempting to connect to database ...

+ echo
+ check_configured
+ case "${DB_DRIVER}" in
+ checkdbinitmysql
+ table=sessions
++ mysql -N -s -h REDACTED -u REDACTED -pREDACTED REDACTED -P 3306 -e 'select count(*) from information_schema.tables where table_schema='\''REDACTED'\'' and table_name='\''sessions'\'';'
+ [[ 1 -eq 1 ]]
+ echo 'Table sessions exists! ...'
+ echo 'Starting Cachet! ...'
+ php artisan config:cache
Table sessions exists! ...
Starting Cachet! ...
Configuration cache cleared!
Configuration cached successfully!
+ /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
2017-08-01 21:50:57,040 INFO supervisord started with pid 52
2017-08-01 21:50:58,042 INFO spawned: 'nginx' with pid 55
2017-08-01 21:50:58,044 INFO spawned: 'php-fpm' with pid 56
2017-08-01 21:50:58,046 INFO spawned: 'queue-worker' with pid 57
[01-Aug-2017 21:50:58] NOTICE: fpm is running, pid 56
[01-Aug-2017 21:50:58] NOTICE: ready to handle connections
2017-08-01 21:50:59,106 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-08-01 21:50:59,106 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-08-01 21:50:59,106 INFO success: queue-worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
10.63.190.222 - - [01/Aug/2017:21:52:37 +0000] "GET /setup HTTP/1.1" 500 3167 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" "-"
```
Stack trace 
```
bash-4.3$ cat storage/logs/laravel-2017-08-01.log 
[2017-08-01 21:50:58] development.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:45
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(25): Illuminate\Encryption\EncryptionServiceProvider->getEncrypterForKeyAndCipher('GWkHxlnV8dWztJT...', 'AES-256-CBC')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build(Object(Closure), Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('encrypter', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('encrypter')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(139): Illuminate\Container\Container->offsetGet('encrypter')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(147): Illuminate\Queue\QueueManager->connection('database')
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, NULL, '2', '1', '3')
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(85): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, NULL, '2', '1', '3')
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(119): Illuminate\Queue\Worker->daemon(NULL, NULL, '2', 128, '1', '3')
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(78): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, NULL, '2', 128, true)
#11 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#14 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main} {"identification":{"id":"ef85f154-10da-4563-af82-5cdcc6c70adf"}} 
```
I have already tried logging into the docker container and running following
```
chmod -R 777 storage
rm -rf bootstrap/cache{,t}/*
rm -rf bootstrap/cache/*
chmod -R 777 bootstrap/
```
nothing seems to work. Can you please point out what I'm doing wrong?

**Comment by djdefi** [comment]
The `APP_KEY` variable requires the `base64:` prefix I believe.

**Comment by ajinkyasuryawanshi-okta** [comment]
That was it sir @djdefi 
Thank you so much for the quick response.

**Comment by jgentes** [comment]
Thanks, this should be in the docs 👍
