### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by DonRichards** [CachetHQ/Docker#236]
### This is my error after doing the following
```terminal
$ docker-compose build
...
$ docker-compose up
```
### Navigated to http://localhost:8818/setup
I tried :8000 with no luck. Looked inside of Docker/Kitematic and it said :8818
![screenshot-localhost-8818-2017-10-13-10-23-07-890](https://user-images.githubusercontent.com/2738244/31550796-85b07268-b000-11e7-8a75-e1110585f987.png)

### After getting the 500 error the terminal was displaying this.
```terminal
cachet_1    | 172.18.0.1 - - [13/Oct/2017:14:25:07 +0000] "GET / HTTP/1.1" 500 3175 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" "-"
cachet_1    | 172.18.0.1 - - [13/Oct/2017:14:25:08 +0000] "GET /favicon.ico HTTP/1.1" 200 952 "http://localhost:8818/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" "-"
cachet_1    | 2017/10/13 14:25:12 [crit] 110#110: *1 connect() to [::1]:9000 failed (99: Address not available) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /setup HTTP/1.1", upstream: "fastcgi://[::1]:9000", host: "localhost:8818"
cachet_1    | 2017/10/13 14:25:12 [warn] 110#110: *1 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /setup HTTP/1.1", upstream: "fastcgi://[::1]:9000", host: "localhost:8818"
cachet_1    | 172.18.0.1 - - [13/Oct/2017:14:25:12 +0000] "GET /setup HTTP/1.1" 500 3175 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" "-"
```

Link to the full log http://pasted.co/a721ff45

```env
APP_ENV="development"
APP_DEBUG="true"
APP_URL="http://localhost"
APP_KEY="nGp/Bhe4hKtsHkGnAnJ2F64bWQ4PZb2ddnD9JEOrLWQ="

DB_DRIVER="pgsql"
DB_HOST="postgres"
DB_DATABASE="postgres"
DB_USERNAME="postgres"
DB_PASSWORD="postgres"
DB_PORT="5432"
DB_PREFIX="chq_"

DOCKER=true

CACHE_DRIVER="apc"
SESSION_DRIVER="apc"
QUEUE_DRIVER="database"

CACHET_EMOJI="false"
CACHET_BEACON="true"
CACHET_AUTO_TWITTER="true"

MAIL_DRIVER="smtp"
MAIL_HOST="localhost"
MAIL_PORT="25"
MAIL_USERNAME="null"
MAIL_PASSWORD="null"
MAIL_ADDRESS="null"
MAIL_NAME="null"
MAIL_ENCRYPTION="null"

REDIS_HOST="null"
REDIS_DATABASE="null"
REDIS_PORT="null"
REDIS_PASSWORD="null"

GITHUB_TOKEN="null"

NEXMO_KEY="null"
NEXMO_SECRET="null"
NEXMO_SMS_FROM="Cachet"
```
### System Information (Mac OS X 10.13)
```terminal
$ docker --version
   Docker version 17.09.0-ce, build afdb6d4
$ vboxmanage --version
   5.1.28r117968
$ docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                            NAMES
5f1931d4ca70        cachetdocker_cachet   "/sbin/entrypoint.sh"    26 minutes ago      Up 29 minutes       80/tcp, 0.0.0.0:8818->8000/tcp   cachetdocker_cachet_1
a0e38cfb0884        postgres:9.5          "docker-entrypoint..."   26 minutes ago      Up 29 minutes       5432/tcp                         cachetdocker_postgres_1
```

**Comment by DonRichards** [comment]
I should note that if I give it http://localhost:8818 I get the same error but I give it a page that doesn't exist like http://localhost:8818/home I get a 404.

**Comment by DonRichards** [comment]
Something worth noting
```json
$ docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "736a5fc9e9b7b67b0335e03bfd01ae25edd7fb85a31f921af33ad46644967628",
        "Created": "2017-10-10T16:22:26.907356526Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
```

**Comment by djdefi** [comment]
Are you able to check the Cachet logs within the container and post them here? You can access them via `docker exec`:

```
# Get current logfile name

$ docker exec -it docker_cachet_1 ls storage/logs/
laravel-2017-06-07.log

# cat logfile:

$ docker exec -it docker_cachet_1 cat storage/logs/laravel-2017-06-07.log
```

**Comment by DonRichards** [comment]
```log
[2017-10-18 20:32:35] development.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:45
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(25): Illuminate\Encryption\EncryptionServiceProvider->getEncrypterForKeyAndCipher('nGp/Bhe4hKtsHkG...', 'AES-256-CBC')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build(Object(Closure), Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('encrypter', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('encrypter')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(139): Illuminate\Container\Container->offsetGet('encrypter')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(147): Illuminate\Queue\QueueManager->connection('database')
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, NULL, '2', '1', '3')
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(86): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, NULL, '2', '1', '3')
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(119): Illuminate\Queue\Worker->daemon(NULL, NULL, '2', 128, '1', '3')
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(78): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, NULL, '2', 128, true)
#11 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#14 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main} {"identification":{"id":"082bec25-a85d-4256-99d4-ab29bb92026a"}} 
[2017-10-18 20:33:21] development.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:45
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(25): Illuminate\Encryption\EncryptionServiceProvider->getEncrypterForKeyAndCipher('nGp/Bhe4hKtsHkG...', 'AES-256-CBC')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build(Object(Closure), Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('encrypter', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('encrypter')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(139): Illuminate\Container\Container->offsetGet('encrypter')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(147): Illuminate\Queue\QueueManager->connection('database')
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, NULL, '2', '1', '3')
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(86): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, NULL, '2', '1', '3')
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(119): Illuminate\Queue\Worker->daemon(NULL, NULL, '2', 128, '1', '3')
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(78): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, NULL, '2', 128, true)
#11 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#14 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main} {"identification":{"id":"d578dc42-e9e3-45b0-9d99-65c20283b0a0"}} 

```

**Comment by djdefi** [comment]
Hi @DonRichards , you will need to include the `base64:` prefix on the `APP_KEY` variable. 

This is the error (somewhat cryptic, I wonder if we can document this better):

```
[2017-10-18 20:33:21] development.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:45
```

**Comment by DonRichards** [comment]
Although that worked (thanks) but the docker configuration automatically set that value. It might be helpful to have the docker scripts concatenate that with the key when it generates the initial setup. Thanks for the help.
