### ISSUE TITLE
No supported encrypter found. The cipher and / or key length are invalid. Using Getting started with Docker Compose docs

### ISSUE THREAD

**Issue by sedan07** [CachetHQ/Docker#330]
Hi,

I've just followed the docs at: https://docs.cachethq.io/docs/get-started-with-docker and when I go to http://localhost I get a 500 error. 

The error recorded in the error logs:
```
cachet_1    | 2018/07/07 19:41:59 [error] 71#71: *21 FastCGI sent in stderr: "PHP message: [2018-07-07 19:41:59] development.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:45
cachet_1    | Stack trace:
cachet_1    | #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(25): Illuminate\Encryption\EncryptionServiceProvider->getEncrypterForKeyAndCipher(NULL, 'AES-256-CBC')
cachet_1    | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
cachet_1    | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build(Object(Closure), Array)
cachet_1    | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('encrypter', Array)
cachet_1    | #4 /var/www/html/vendor/laravel/f" while reading response header from upstream, client: 172.24.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
cachet_1    | 172.24.0.1 - - [07/Jul/2018:19:41:59 +0000] "GET / HTTP/1.1" 500 3165 "http://localhost/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.181 Chrome/66.0.3359.181 Safari/537.36" "-"
cachet_1    | [07-Jul-2018 19:41:59] WARNING: [pool www] child 250 said into stderr: "NOTICE: PHP message: [2018-07-07 19:41:59] development.ERROR: RuntimeException: AES-256-CBC No supported encrypter found. The cipher and / or key length are invalid. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:45"
cachet_1    | [07-Jul-2018 19:41:59] WARNING: [pool www] child 250 said into stderr: "Stack trace:"
cachet_1    | [07-Jul-2018 19:41:59] WARNING: [pool www] child 250 said into stderr: "#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(25): Illuminate\Encryption\EncryptionServiceProvider->getEncrypterForKeyAndCipher(NULL, 'AES-256-CBC')"
cachet_1    | [07-Jul-2018 19:41:59] WARNING: [pool www] child 250 said into stderr: "#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)"
cachet_1    | [07-Jul-2018 19:41:59] WARNING: [pool www] child 250 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build(Object(Closure), Array)"
cachet_1    | [07-Jul-2018 19:41:59] WARNING: [pool www] child 250 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('encrypter', Array)"
```

I've tried the suggestions of:
```
php artisan key:generate
php artisan config:cache
```

But these make no difference. I've followed the docs exactly and it doesn't work out the box? is there an extra undocumented step I need?

Tried the version mentioned in the docs: `v2.3.10` and `v2.3.15` and master and no joy with any.

**Comment by jbrooksuk** [comment]
@djdefi could you investigate please?

**Comment by jasimmonsv** [comment]
the API_KEY passed has to be a length of 32 as defined in Encrypter.php. As soon as I passed in a 32 char string, this error went away and everything came right up.
