### ISSUE TITLE
Docker setup fails with cachet:install not defined

### ISSUE THREAD

**Issue by CaTaDeVoPs** [CachetHQ/Docker#379]
Hello,

Following the steps and using latest version v2.3.18 i receive this:

cachet_1    | [2020-06-03 14:40:36] production.ERROR: Symfony\Component\Console\Exception\CommandNotFoundException: Command "cachet:install" is not defined.
cachet_1    |
cachet_1    | Did you mean one of these?
cachet_1    |     app:install
cachet_1    |     migrate:install
cachet_1    |
cachet_1    |     cachet:metrics
cachet_1    |     cachet:seed
cachet_1    |     cache:clear
cachet_1    |     cache:table in /var/www/html/vendor/symfony/console/Application.php:515
cachet_1    | Stack trace:
cachet_1    | #0 /var/www/html/vendor/symfony/console/Application.php(183): Symfony\Component\Console\Application->find('cachet:install')
cachet_1    | #1 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
cachet_1    | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
cachet_1    | #3 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by ryan77627** [comment]
I had the same issue. Edit entrypoint.sh and change `php artisan cachet:install --no-interaction` on line 207 to `php artisan app:install --no-interaction` and it should launch successfully.

**Comment by ryan77627** [comment]
Oh also, make sure you set the proper options to APC, (I forget what they were called sorry). and make sure you change the Dockerfile to have `FROM nginx:1.14.0-alpine` instead of whatever was there before (again, forgot, sorry). This is because the image they pull from by default has php packages that are too new.

**Comment by bmaximuml** [comment]
I'm seeing the same error, fixed by rebuilding with `app:install` instead of `cachet:install` in entrypoint.sh.
