### ISSUE TITLE
Migrating from 2.3.15 to 2.3.18 does not work

### ISSUE THREAD

**Issue by johan-smits** [cachethq/Docker#397]
When upgrading the container stops working. Did not see any changes in the changelog that might need configuration changes.

Here is a log of the console output:

```
172.31.19.170 - - [15/Jan/2021:08:17:34 +0000] "GET / HTTP/1.1" 500 581781 "-" "kube-probe/1.18+" "-"
2021/01/15 08:17:34 [error] 73#73: *9 FastCGI sent in stderr: "PHP message: [2021-01-15 08:17:34] production.ERROR: ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1161
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/html/v...', 1161, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1161): count(NULL)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1395): Illuminate\Database\Eloquent\Builder->callScope(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('notScheduled', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3505): call_user_func_array(Array, Array)
#5 [internal function]: Illuminate\Database\Eloquent\Model->__call('notScheduled', Array)
#6 /var/www/html/vendor/laravel/framework/src/" while reading response header from upstream, client: 172.31.19.170, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "172.31.16.158:8000"
2021/01/15 08:17:34 [warn] 73#73: *9 an upstream response is buffered to a temporary file /tmp/fastcgi/4/00/0000000004 while reading upstream, client: 172.31.19.170, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "172.31.16.158:8000"
[15-Jan-2021 08:17:57] WARNING: [pool www] child 84 said into stderr: "NOTICE: PHP message: [2021-01-15 08:17:57] production.ERROR: ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1161"
[15-Jan-2021 08:17:57] WARNING: [pool www] child 84 said into stderr: "Stack trace:"
[15-Jan-2021 08:17:57] WARNING: [pool www] child 84 said into stderr: "#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/html/v...', 1161, Array)"
[15-Jan-2021 08:17:57] WARNING: [pool www] child 84 said into stderr: "#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1161): count(NULL)"
[15-Jan-2021 08:17:57] WARNING: [pool www] child 84 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1395): Illuminate\Database\Eloquent\Builder->callScope(Array, Array)"
[15-Jan-2021 08:17:57] WARNING: [pool www] child 84 said into stderr: "#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('notScheduled', Array)"
[15-Jan-2021 08:17:57] WARNING: [pool www] child 84 said into stderr: "#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3505): call_user_func_array(Array, Array)"
[15-Jan-2021 08:17:57] WARNING: [pool www] child 84 said into stderr: "#5 [internal function]: Illuminate\Database\Eloquent\Model->__call('notScheduled', Array)"
[15-Jan-2021 08:17:57] WARNING: [pool www] child 84 said into stderr: "#6 /var/www/html/vendor/laravel/framework/src/..."
172.31.19.170 - - [15/Jan/2021:08:17:57 +0000] "GET / HTTP/1.1" 500 391646 "-" "kube-probe/1.18+" "-"
2021/01/15 08:17:57 [error] 73#73: *11 FastCGI sent in stderr: "PHP message: [2021-01-15 08:17:57] production.ERROR: ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1161
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/html/v...', 1161, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1161): count(NULL)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1395): Illuminate\Database\Eloquent\Builder->callScope(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('notScheduled', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3505): call_user_func_array(Array, Array)
#5 [internal function]: Illuminate\Database\Eloquent\Model->__call('notScheduled', Array)
#6 /var/www/html/vendor/laravel/framework/src/" while reading response header from upstream, client: 172.31.19.170, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "172.31.16.158:8000"
2021/01/15 08:17:57 [warn] 73#73: *11 an upstream response is buffered to a temporary file /tmp/fastcgi/5/00/0000000005 while reading upstream, client: 172.31.19.170, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "172.31.16.158:8000"
```

**Comment by alexsanderp** [comment]
I have the same problem

**Comment by mahernoz-d** [comment]
I too have the same problem

**Comment by johan-smits** [comment]
@mahernoz-d @alexsanderp did one of you already solved this?
