### ISSUE TITLE
Error in setup page

### ISSUE THREAD

**Issue by esteban1983cl** [cachethq/Docker#413]
Hi team, I trying to start cachet in docker, I'm getting the following error when I finish setup:

```shell
2021/07/13 18:49:48 [error] 73#73: *4 FastCGI sent in stderr: "PHP message: [2021-07-13 18:49:48] production.ERROR: ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1161
cachet_1    | Stack trace:
cachet_1    | #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/html/v...', 1161, Array)
cachet_1    | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1161): count(NULL)
cachet_1    | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1192): Illuminate\Database\Eloquent\Builder->callScope(Object(Closure))
cachet_1    | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(314): Illuminate\Database\Eloquent\Builder->applyScopes()
cachet_1    | #4 /var/www/html/app/Http/Controllers/Dashboard/DashboardController.php(79): Illuminate\Database\Eloquent\Builder->get()
cachet_1    | #5 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\DashboardController" while reading response header from upstream, client: 172.23.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:8000", referrer: "http://localhost:8000/setup"
```

Cachet version v2.3.18
Can you help me please, thanks

**Comment by veenarm** [comment]
Getting the same error :(
